# db.py
def criar_tabela(conn):
    try:
        cursor = conn.cursor()
        # Verifica se a tabela já existe
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM all_tables
            WHERE table_name = 'DADOS_CLIMATICOS'
        """
        )
        count = cursor.fetchone()[0]

        if count == 0:  # A tabela não existe
            cursor.execute(
                """
                CREATE TABLE dados_climaticos (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    data_hora TIMESTAMP,
                    temperatura NUMBER,
                    precipitacao NUMBER
                )
            """
            )
            conn.commit()
            print("Tabela criada com sucesso!")
        else:
            print("A tabela 'dados_climaticos' já existe.")
    except Exception as e:
        print("Erro ao criar tabela:", e)
